ML ZOOMCAMP WEEK 3 HOUSING PRICES: LOGISTIC REGRESSION

In [80]:
import pandas as pd
import numpy as np

In [81]:
#Dataset HOUSING

df=pd.read_csv("housing.csv")
df.head()

#The goal of this homework is to create a regression model for predicting housing prices (column 'median_house_value').

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0    -122.23     37.88                41.0        880.0           129.0   
1    -122.22     37.86                21.0       7099.0          1106.0   
2    -122.24     37.85                52.0       1467.0           190.0   
3    -122.25     37.85                52.0       1274.0           235.0   
4    -122.25     37.85                52.0       1627.0           280.0   

   population  households  median_income  median_house_value ocean_proximity  
0       322.0       126.0         8.3252            452600.0        NEAR BAY  
1      2401.0      1138.0         8.3014            358500.0        NEAR BAY  
2       496.0       177.0         7.2574            352100.0        NEAR BAY  
3       558.0       219.0         5.6431            341300.0        NEAR BAY  
4       565.0       259.0         3.8462            342200.0        NEAR BAY

In [82]:
df_1=df[["longitude","latitude","housing_median_age","total_rooms","total_bedrooms","population",
         "households","median_income","median_house_value","ocean_proximity"]]

df_1

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0        -122.23     37.88                41.0        880.0           129.0   
1        -122.22     37.86                21.0       7099.0          1106.0   
2        -122.24     37.85                52.0       1467.0           190.0   
3        -122.25     37.85                52.0       1274.0           235.0   
4        -122.25     37.85                52.0       1627.0           280.0   
...          ...       ...                 ...          ...             ...   
20635    -121.09     39.48                25.0       1665.0           374.0   
20636    -121.21     39.49                18.0        697.0           150.0   
20637    -121.22     39.43                17.0       2254.0           485.0   
20638    -121.32     39.43                18.0       1860.0           409.0   
20639    -121.24     39.37                16.0       2785.0           616.0   

       population  households  median_income  median_house_value  \
0           322.0       126.0         8.3252            452600.0   
1          2401.0      1138.0         8.3014            358500.0   
2           496.0       177.0         7.2574            352100.0   
3           558.0       219.0         5.6431            341300.0   
4           565.0       259.0         3.8462            342200.0   
...           ...         ...            ...                 ...   
20635       845.0       330.0         1.5603             78100.0   
20636       356.0       114.0         2.5568             77100.0   
20637      1007.0       433.0         1.7000             92300.0   
20638       741.0       349.0         1.8672             84700.0   
20639      1387.0       530.0         2.3886             89400.0   

      ocean_proximity  
0            NEAR BAY  
1            NEAR BAY  
2            NEAR BAY  
3            NEAR BAY  
4            NEAR BAY  
...               ...  
20635          INLAND  
20636          INLAND  
20637          INLAND  
20638          INLAND  
20639          INLAND  

[20640 rows x 10 columns]

In [83]:
#MISSING VALUES

df_1.isnull().sum() #207 in total_bedrooms

longitude               0
latitude                0
housing_median_age      0
total_rooms             0
total_bedrooms        207
population              0
households              0
median_income           0
median_house_value      0
ocean_proximity         0
dtype: int64

In [84]:
df_1=df_1.fillna(0)
df_1.isnull().sum() # no missing values

longitude             0
latitude              0
housing_median_age    0
total_rooms           0
total_bedrooms        0
population            0
households            0
median_income         0
median_house_value    0
ocean_proximity       0
dtype: int64

In [85]:
df_1["rooms_per_household"]=df_1["total_rooms"]/df_1["households"]
df_1["bedrooms_per_room"]=df_1["total_bedrooms"]/df_1["total_rooms"]
df_1["population_per_household"]=df_1["population"]/df_1["households"]
df_1.head()

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0    -122.23     37.88                41.0        880.0           129.0   
1    -122.22     37.86                21.0       7099.0          1106.0   
2    -122.24     37.85                52.0       1467.0           190.0   
3    -122.25     37.85                52.0       1274.0           235.0   
4    -122.25     37.85                52.0       1627.0           280.0   

   population  households  median_income  median_house_value ocean_proximity  \
0       322.0       126.0         8.3252            452600.0        NEAR BAY   
1      2401.0      1138.0         8.3014            358500.0        NEAR BAY   
2       496.0       177.0         7.2574            352100.0        NEAR BAY   
3       558.0       219.0         5.6431            341300.0        NEAR BAY   
4       565.0       259.0         3.8462            342200.0        NEAR BAY   

   rooms_per_household  bedrooms_per_room  population_per_household  
0             6.984127           0.146591                  2.555556  
1             6.238137           0.155797                  2.109842  
2             8.288136           0.129516                  2.802260  
3             5.817352           0.184458                  2.547945  
4             6.281853           0.172096                  2.181467

In [86]:
#Question 1
#What is the most frequent observation (mode) for the column ocean_proximity?

df_1["ocean_proximity"].mode()


0    <1H OCEAN
Name: ocean_proximity, dtype: object

In [87]:
df_1.groupby("ocean_proximity").count()

longitude  latitude  housing_median_age  total_rooms  \
ocean_proximity                                                         
<1H OCEAN             9136      9136                9136         9136   
INLAND                6551      6551                6551         6551   
ISLAND                   5         5                   5            5   
NEAR BAY              2290      2290                2290         2290   
NEAR OCEAN            2658      2658                2658         2658   

                 total_bedrooms  population  households  median_income  \
ocean_proximity                                                          
<1H OCEAN                  9136        9136        9136           9136   
INLAND                     6551        6551        6551           6551   
ISLAND                        5           5           5              5   
NEAR BAY                   2290        2290        2290           2290   
NEAR OCEAN                 2658        2658        2658           2658   

                 median_house_value  rooms_per_household  bedrooms_per_room  \
ocean_proximity                                                               
<1H OCEAN                      9136                 9136               9136   
INLAND                         6551                 6551               6551   
ISLAND                            5                    5                  5   
NEAR BAY                       2290                 2290               2290   
NEAR OCEAN                     2658                 2658               2658   

                 population_per_household  
ocean_proximity                            
<1H OCEAN                            9136  
INLAND                               6551  
ISLAND                                  5  
NEAR BAY                             2290  
NEAR OCEAN                           2658

In [88]:
#Question 
#Create the correlation matrix for the numerical features of your train dataset.
#In a correlation matrix, you compute the correlation coefficient between every pair of features in the dataset.
#What are the two features that have the biggest correlation in this dataset?

df_1.dtypes


longitude                   float64
latitude                    float64
housing_median_age          float64
total_rooms                 float64
total_bedrooms              float64
population                  float64
households                  float64
median_income               float64
median_house_value          float64
ocean_proximity              object
rooms_per_household         float64
bedrooms_per_room           float64
population_per_household    float64
dtype: object

In [128]:
numerical=["longitude","latitude","housing_median_age","total_rooms","total_bedrooms","population",
         "households","median_income","rooms_per_household","bedrooms_per_room","population_per_household"]
numerical
categorical=["ocean_proximity"]
df_1[numerical]

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0        -122.23     37.88                41.0        880.0           129.0   
1        -122.22     37.86                21.0       7099.0          1106.0   
2        -122.24     37.85                52.0       1467.0           190.0   
3        -122.25     37.85                52.0       1274.0           235.0   
4        -122.25     37.85                52.0       1627.0           280.0   
...          ...       ...                 ...          ...             ...   
20635    -121.09     39.48                25.0       1665.0           374.0   
20636    -121.21     39.49                18.0        697.0           150.0   
20637    -121.22     39.43                17.0       2254.0           485.0   
20638    -121.32     39.43                18.0       1860.0           409.0   
20639    -121.24     39.37                16.0       2785.0           616.0   

       population  households  median_income  rooms_per_household  \
0           322.0       126.0         8.3252             6.984127   
1          2401.0      1138.0         8.3014             6.238137   
2           496.0       177.0         7.2574             8.288136   
3           558.0       219.0         5.6431             5.817352   
4           565.0       259.0         3.8462             6.281853   
...           ...         ...            ...                  ...   
20635       845.0       330.0         1.5603             5.045455   
20636       356.0       114.0         2.5568             6.114035   
20637      1007.0       433.0         1.7000             5.205543   
20638       741.0       349.0         1.8672             5.329513   
20639      1387.0       530.0         2.3886             5.254717   

       bedrooms_per_room  population_per_household  
0               0.146591                  2.555556  
1               0.155797                  2.109842  
2               0.129516                  2.802260  
3               0.184458                  2.547945  
4               0.172096                  2.181467  
...                  ...                       ...  
20635           0.224625                  2.560606  
20636           0.215208                  3.122807  
20637           0.215173                  2.325635  
20638           0.219892                  2.123209  
20639           0.221185                  2.616981  

[20640 rows x 11 columns]

In [90]:
df_1[categorical]

ocean_proximity
0            NEAR BAY
1            NEAR BAY
2            NEAR BAY
3            NEAR BAY
4            NEAR BAY
...               ...
20635          INLAND
20636          INLAND
20637          INLAND
20638          INLAND
20639          INLAND

[20640 rows x 1 columns]

In [91]:
df_1[numerical].corr() #Matriz de correlacion
#total_bedrooms and households 0.9665 <- CORRECT ANSWER
#total_bedrooms and total_rooms 0.9201
#population and households 0.9072
#population_per_household and total_rooms -0.0245

longitude  latitude  housing_median_age  \
longitude                  1.000000 -0.924664           -0.108197   
latitude                  -0.924664  1.000000            0.011173   
housing_median_age        -0.108197  0.011173            1.000000   
total_rooms                0.044568 -0.036100           -0.361262   
total_bedrooms             0.068082 -0.065318           -0.317063   
population                 0.099773 -0.108785           -0.296244   
households                 0.055310 -0.071035           -0.302916   
median_income             -0.015176 -0.079809           -0.119034   
median_house_value        -0.045967 -0.144160            0.105623   
rooms_per_household       -0.027540  0.106389           -0.153277   
bedrooms_per_room          0.084836 -0.104112            0.125396   
population_per_household   0.002476  0.002366            0.013191   

                          total_rooms  total_bedrooms  population  households  \
longitude                    0.044568        0.068082    0.099773    0.055310   
latitude                    -0.036100       -0.065318   -0.108785   -0.071035   
housing_median_age          -0.361262       -0.317063   -0.296244   -0.302916   
total_rooms                  1.000000        0.920196    0.857126    0.918484   
total_bedrooms               0.920196        1.000000    0.866266    0.966507   
population                   0.857126        0.866266    1.000000    0.907222   
households                   0.918484        0.966507    0.907222    1.000000   
median_income                0.198050       -0.007295    0.004834    0.013033   
median_house_value           0.134153        0.049148   -0.024650    0.065843   
rooms_per_household          0.133798        0.002717   -0.072213   -0.080598   
bedrooms_per_room           -0.174583        0.122205    0.031397    0.059818   
population_per_household    -0.024581       -0.028019    0.069863   -0.027309   

                          median_income  median_house_value  \
longitude                     -0.015176           -0.045967   
latitude                      -0.079809           -0.144160   
housing_median_age            -0.119034            0.105623   
total_rooms                    0.198050            0.134153   
total_bedrooms                -0.007295            0.049148   
population                     0.004834           -0.024650   
households                     0.013033            0.065843   
median_income                  1.000000            0.688075   
median_house_value             0.688075            1.000000   
rooms_per_household            0.326895            0.151948   
bedrooms_per_room             -0.573836           -0.238759   
population_per_household       0.018766           -0.023737   

                          rooms_per_household  bedrooms_per_room  \
longitude                           -0.027540           0.084836   
latitude                             0.106389          -0.104112   
housing_median_age                  -0.153277           0.125396   
total_rooms                          0.133798          -0.174583   
total_bedrooms                       0.002717           0.122205   
population                          -0.072213           0.031397   
households                          -0.080598           0.059818   
median_income                        0.326895          -0.573836   
median_house_value                   0.151948          -0.238759   
rooms_per_household                  1.000000          -0.387465   
bedrooms_per_room                   -0.387465           1.000000   
population_per_household            -0.004852           0.003047   

                          population_per_household  
longitude                                 0.002476  
latitude                                  0.002366  
housing_median_age                        0.013191  
total_rooms                              -0.024581  
total_bedrooms                           -0.028019  
population                                0.069863 

In [92]:
#Make median_house_value binary
#We need to turn the median_house_value variable from numeric into binary.
#Let's create a variable above_average which is 1 if the median_house_value is above its mean value and 0 otherwise.

df_1["median_house_value"].nunique()

3842

In [93]:
df_1["median_house_value"].mean()

206855.81690891474

In [94]:
(df_1["median_house_value"]>=df_1["median_house_value"].mean()).astype(int)

0        1
1        1
2        1
3        1
4        1
        ..
20635    0
20636    0
20637    0
20638    0
20639    0
Name: median_house_value, Length: 20640, dtype: int32

In [95]:
df_1["above_average"]=(df_1["median_house_value"]>=df_1["median_house_value"].mean()).astype(int)
df_1

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0        -122.23     37.88                41.0        880.0           129.0   
1        -122.22     37.86                21.0       7099.0          1106.0   
2        -122.24     37.85                52.0       1467.0           190.0   
3        -122.25     37.85                52.0       1274.0           235.0   
4        -122.25     37.85                52.0       1627.0           280.0   
...          ...       ...                 ...          ...             ...   
20635    -121.09     39.48                25.0       1665.0           374.0   
20636    -121.21     39.49                18.0        697.0           150.0   
20637    -121.22     39.43                17.0       2254.0           485.0   
20638    -121.32     39.43                18.0       1860.0           409.0   
20639    -121.24     39.37                16.0       2785.0           616.0   

       population  households  median_income  median_house_value  \
0           322.0       126.0         8.3252            452600.0   
1          2401.0      1138.0         8.3014            358500.0   
2           496.0       177.0         7.2574            352100.0   
3           558.0       219.0         5.6431            341300.0   
4           565.0       259.0         3.8462            342200.0   
...           ...         ...            ...                 ...   
20635       845.0       330.0         1.5603             78100.0   
20636       356.0       114.0         2.5568             77100.0   
20637      1007.0       433.0         1.7000             92300.0   
20638       741.0       349.0         1.8672             84700.0   
20639      1387.0       530.0         2.3886             89400.0   

      ocean_proximity  rooms_per_household  bedrooms_per_room  \
0            NEAR BAY             6.984127           0.146591   
1            NEAR BAY             6.238137           0.155797   
2            NEAR BAY             8.288136           0.129516   
3            NEAR BAY             5.817352           0.184458   
4            NEAR BAY             6.281853           0.172096   
...               ...                  ...                ...   
20635          INLAND             5.045455           0.224625   
20636          INLAND             6.114035           0.215208   
20637          INLAND             5.205543           0.215173   
20638          INLAND             5.329513           0.219892   
20639          INLAND             5.254717           0.221185   

       population_per_household  above_average  
0                      2.555556              1  
1                      2.109842              1  
2                      2.802260              1  
3                      2.547945              1  
4                      2.181467              1  
...                         ...            ...  
20635                  2.560606              0  
20636                  3.122807              0  
20637                  2.325635              0  
20638                  2.123209              0  
20639                  2.616981              0  

[20640 rows x 14 columns]

In [96]:
#Split the data
#Split your data in train/val/test sets, with 60%/20%/20% distribution.
#Use Scikit-Learn for that (the train_test_split function) and set the seed to 42.
#Make sure that the target value (median_house_value) is not in your dataframe.

from sklearn.model_selection import train_test_split

df_full_train, df_test=train_test_split(df_1, test_size=0.2, random_state=42)
len(df_full_train), len(df_test)

(16512, 4128)

In [97]:
df_train, df_val=train_test_split(df_full_train, test_size=0.25, random_state=42) #20% sobre 80% = 1/4
len(df_train), len(df_val), len(df_test)

(12384, 4128, 4128)

In [98]:
df_train=df_train.reset_index(drop=True)
df_val=df_val.reset_index(drop=True)
df_test=df_test.reset_index(drop=True)

df_train.head()

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0    -119.67     34.43                39.0       1467.0           381.0   
1    -118.32     33.74                24.0       6097.0           794.0   
2    -121.62     39.13                41.0       1317.0           309.0   
3    -118.63     34.24                 9.0       4759.0           924.0   
4    -122.30     37.52                38.0       2769.0           387.0   

   population  households  median_income  median_house_value ocean_proximity  \
0      1404.0       374.0         2.3681            241400.0       <1H OCEAN   
1      2248.0       806.0        10.1357            500001.0      NEAR OCEAN   
2       856.0       337.0         1.6719             64100.0          INLAND   
3      1884.0       915.0         4.8333            277200.0       <1H OCEAN   
4       994.0       395.0         5.5902            417000.0      NEAR OCEAN   

   rooms_per_household  bedrooms_per_room  population_per_household  \
0             3.922460           0.259714                  3.754011   
1             7.564516           0.130228                  2.789082   
2             3.908012           0.234624                  2.540059   
3             5.201093           0.194158                  2.059016   
4             7.010127           0.139762                  2.516456   

   above_average  
0              1  
1              1  
2              0  
3              1  
4              1

In [143]:
y_train=df_train.above_average.values
y_val=df_val.above_average.values
y_test=df_test.above_average.values
y_train

array([1, 1, 0, ..., 1, 0, 0])

In [100]:
del df_train["median_house_value"]
del df_val["median_house_value"]
del df_test["median_house_value"]

df_train.head()

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0    -119.67     34.43                39.0       1467.0           381.0   
1    -118.32     33.74                24.0       6097.0           794.0   
2    -121.62     39.13                41.0       1317.0           309.0   
3    -118.63     34.24                 9.0       4759.0           924.0   
4    -122.30     37.52                38.0       2769.0           387.0   

   population  households  median_income ocean_proximity  rooms_per_household  \
0      1404.0       374.0         2.3681       <1H OCEAN             3.922460   
1      2248.0       806.0        10.1357      NEAR OCEAN             7.564516   
2       856.0       337.0         1.6719          INLAND             3.908012   
3      1884.0       915.0         4.8333       <1H OCEAN             5.201093   
4       994.0       395.0         5.5902      NEAR OCEAN             7.010127   

   bedrooms_per_room  population_per_household  above_average  
0           0.259714                  3.754011              1  
1           0.130228                  2.789082              1  
2           0.234624                  2.540059              0  
3           0.194158                  2.059016              1  
4           0.139762                  2.516456              1

In [101]:
#Question 3
#Calculate the mutual information score with the (binarized) price for the categorical variable that we have. Use the training set only.
#What is the value of mutual information?
#Round it to 2 decimal digits using round(score, 2)

from sklearn.metrics import mutual_info_score
score=mutual_info_score(df_train.ocean_proximity, df_train.above_average)
round(score,2)

0.1

In [102]:
#Question 4
#Now let's train a logistic regression
#Remember that we have one categorical variable ocean_proximity in the data. Include it using one-hot encoding.
#Fit the model on the training dataset.
#To make sure the results are reproducible across different versions of Scikit-Learn, fit the model with these parameters:
#model = LogisticRegression(solver="liblinear", C=1.0, max_iter=1000, random_state=42)
#Calculate the accuracy on the validation dataset and round it to 2 decimal digits.

from sklearn.feature_extraction import DictVectorizer

In [144]:
dicts=df_train[["ocean_proximity"]].iloc[:5]
dicts

ocean_proximity
0       <1H OCEAN
1      NEAR OCEAN
2          INLAND
3       <1H OCEAN
4      NEAR OCEAN

In [145]:
dicts=df_train[["ocean_proximity"]].iloc[:50].to_dict(orient="records")
dicts

[{'ocean_proximity': '<1H OCEAN'},
 {'ocean_proximity': 'NEAR OCEAN'},
 {'ocean_proximity': 'INLAND'},
 {'ocean_proximity': '<1H OCEAN'},
 {'ocean_proximity': 'NEAR OCEAN'},
 {'ocean_proximity': 'NEAR OCEAN'},
 {'ocean_proximity': '<1H OCEAN'},
 {'ocean_proximity': '<1H OCEAN'},
 {'ocean_proximity': '<1H OCEAN'},
 {'ocean_proximity': 'INLAND'},
 {'ocean_proximity': 'NEAR OCEAN'},
 {'ocean_proximity': '<1H OCEAN'},
 {'ocean_proximity': '<1H OCEAN'},
 {'ocean_proximity': 'NEAR OCEAN'},
 {'ocean_proximity': 'INLAND'},
 {'ocean_proximity': 'INLAND'},
 {'ocean_proximity': 'NEAR BAY'},
 {'ocean_proximity': 'INLAND'},
 {'ocean_proximity': 'INLAND'},
 {'ocean_proximity': 'INLAND'},
 {'ocean_proximity': 'NEAR BAY'},
 {'ocean_proximity': 'NEAR BAY'},
 {'ocean_proximity': 'INLAND'},
 {'ocean_proximity': 'NEAR OCEAN'},
 {'ocean_proximity': 'NEAR BAY'},
 {'ocean_proximity': '<1H OCEAN'},
 {'ocean_proximity': '<1H OCEAN'},
 {'ocean_proximity': '<1H OCEAN'},
 {'ocean_proximity': '<1H OCEAN'},
 {'ocea

In [146]:
dv=DictVectorizer(sparse=False)
dv

DictVectorizer(sparse=False)

In [147]:
trains_dicts=df_train[categorical+numerical].to_dict(orient="records")
trains_dicts[0]

{'ocean_proximity': '<1H OCEAN',
 'longitude': -119.67,
 'latitude': 34.43,
 'housing_median_age': 39.0,
 'total_rooms': 1467.0,
 'total_bedrooms': 381.0,
 'population': 1404.0,
 'households': 374.0,
 'median_income': 2.3681,
 'rooms_per_household': 3.9224598930481283,
 'bedrooms_per_room': 0.25971370143149286,
 'population_per_household': 3.7540106951871657}

In [148]:
dv.fit(trains_dicts)
dv.transform(trains_dicts)

array([[2.59713701e-01, 3.74000000e+02, 3.90000000e+01, ...,
        3.92245989e+00, 3.81000000e+02, 1.46700000e+03],
       [1.30227981e-01, 8.06000000e+02, 2.40000000e+01, ...,
        7.56451613e+00, 7.94000000e+02, 6.09700000e+03],
       [2.34624146e-01, 3.37000000e+02, 4.10000000e+01, ...,
        3.90801187e+00, 3.09000000e+02, 1.31700000e+03],
       ...,
       [1.82879377e-01, 6.02000000e+02, 1.80000000e+01, ...,
        5.54983389e+00, 6.11000000e+02, 3.34100000e+03],
       [2.29126214e-01, 3.50000000e+02, 1.60000000e+01, ...,
        4.41428571e+00, 3.54000000e+02, 1.54500000e+03],
       [2.09574468e-01, 2.15000000e+02, 3.50000000e+01, ...,
        4.37209302e+00, 1.97000000e+02, 9.40000000e+02]])

In [149]:
X_train=dv.fit_transform(trains_dicts)
X_train
X_train.shape

(12384, 16)

In [150]:
val_dicts=df_val[categorical+numerical].to_dict(orient="records")
X_val=dv.transform(val_dicts)
X_val.shape

(4128, 16)

In [151]:
#Regresion logistica con scikit learn

from sklearn.linear_model import LogisticRegression
model = LogisticRegression(solver="liblinear", C=1.0, max_iter=1000, random_state=42)

In [152]:
model=LogisticRegression()
model.fit(X_train, y_train)

C:\Users\Matias\anaconda3\envs\ml-zoomcamp\lib\site-packages\sklearn\linear_model\_logistic.py:444: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [153]:
model.coef_[0].round(3)

array([-0.003,  0.01 ,  0.034, -0.366, -0.058,  0.845,  0.16 , -0.231,
        0.   ,  0.025,  0.045, -0.002,  0.086,  0.16 , -0.003, -0.   ])

In [154]:
model.intercept_[0]

0.00012014128376234423

In [155]:
model.predict(X_train) #hard prediction

array([0, 1, 0, ..., 0, 1, 1])

In [156]:
model.predict_proba(X_train) #soft prediction #prob de ser negativo, y prob de ser positiv

array([[0.84096701, 0.15903299],
       [0.00293671, 0.99706329],
       [0.96221962, 0.03778038],
       ...,
       [0.51240662, 0.48759338],
       [0.32329738, 0.67670262],
       [0.38183277, 0.61816723]])

In [157]:
model.predict_proba(X_train)[:,1] #elegimos la columna de 1 o sea de ser positivo
y_pred=model.predict_proba(X_val)[:,1] #elegimos la columna de 1 o sea de ser positivo
y_pred
y_pred>=0.5 #true is mayor que el promedio


array([False, False,  True, ...,  True,  True, False])

In [159]:
above_avg=(y_pred>=0.5)
above_avg.shape

(4128,)

In [167]:
df_val[above_avg].index

Int64Index([   2,    3,    4,    8,   13,   14,   17,   20,   24,   25,
            ...
            4103, 4104, 4110, 4111, 4114, 4116, 4121, 4124, 4125, 4126],
           dtype='int64', length=1614)

In [168]:
y_val

array([0, 0, 1, ..., 1, 1, 0])

In [169]:
y_val==above_avg.astype(int)

array([ True,  True,  True, ...,  True,  True,  True])

In [170]:
(y_val==above_avg.astype(int)).mean() #Accuracy 80,69%

0.8069282945736435

In [1]:
#Question 5
#Let's find the least useful feature using the feature elimination technique.
#Train a model with all these features (using the same parameters as in Q4).
#Now exclude each feature from this set and train a model without it. Record the accuracy for each model.
#For each feature, calculate the difference between the original accuracy and the accuracy without the feature.

#note: the difference doesn't have to be positive




In [ ]:
#Question 6
#For this question, we'll see how to use a linear regression model from Scikit-Learn
#We'll need to use the original column 'median_house_value'. Apply the logarithmic transformation to this column.
#Fit the Ridge regression model (model = Ridge(alpha=a, solver="sag", random_state=42)) on the training data.
#This model has a parameter alpha. Let's try the following values: [0, 0.01, 0.1, 1, 10]
#Which of these alphas leads to the best RMSE on the validation set? Round your RMSE scores to 3 decimal digits.
#If there are multiple options, select the smallest alpha.

